# markets.py
FOOTBALL_MARKETS = [
    # screen 1
    ("kazdy_tym_gol_prvni_polo", "Každý tým dá v 1. poločasu"),
    ("hc_prvni_polo", "Handicap 1. poločas"),
    ("goly_prvni_polo_presne", "Počet gólů v 1. poločasu (přesně)"),
    ("vysledek_v_case", "Výsledek v čase"),
    ("goly_mezi_minutami", "Počet gólů mezi minutami"),
    ("prvni_gol_kdy", "Kdy bude vstřelen 1. gól v zápasu"),
    ("oba_polo_alespon1", "V každém poločase padne 1 a více gólů"),
    ("ktery_polo_nejvic", "Ve kterém poločase padne nejvíce gólů"),
    ("nasok_viteze", "Jaký bude gólový náskok vítěze zápasu"),
    ("vysledek_a_pocet", "Výsledek zápasu a počet gólů v zápasu"),
    ("presny_vysledek", "Přesný výsledek zápasu"),
    ("presny_prvni_polo", "Přesný výsledek 1. poločasu"),
    ("prvni_polo_a_zapas", "Výsledek 1. poločasu a výsledek zápasu"),
    ("prvni_polo_nebo_zapas", "Výsledek 1. poločasu nebo výsledek zápasu"),
    ("zapas_a_prvni_gol", "Výsledek zápasu a první gól"),
    ("tym_vyhraje_alespon_polo", "Tým vyhraje alespoň jeden poločas"),
    ("tym_vyhraje_oba_pola", "Tým vyhraje oba poločasy"),
    ("tym_gol_v_obou_polech", "Tým dá gól v obou poločasech"),
    ("oba_tymy_gol_v_obou_polech", "Každý tým dá gól v obou poločasech"),
    ("prohrava_a_vyhraje", "Tým bude prohrávat a vyhraje v zápasu"),
    # screen 2
    ("1x2", "Výsledek zápasu"),
    ("vyhra_nebo_povede_o2", "Vyhraje zápas nebo povede o 2 góly"),
    ("kdo_da_v_zapase", "Kdo dá v zápasu"),
    ("goly_celkem", "Počet gólů v zápasu"),
    ("goly_tymu_celkem", "Počet gólů týmu v zápasu"),
    ("bez_remizy", "Výsledek zápasu bez remízy"),
    ("oba_tymy_gol", "Každý tým dá v zápasu"),
    ("vysledek_a_goly_tymu", "Výsledek zápasu a góly týmů"),
    ("goly_celkem_a_tymy", "Počet gólů v zápasu a góly týmů"),
    ("handicap", "Handicap v zápasu"),
    ("goly_celkem_presne", "Počet gólů v zápasu (přesně)"),
    ("vysledek_prvni_polo", "Výsledek 1. poločasu"),
    ("vysledek_druhy_polo", "Výsledek 2. poločasu"),
    ("goly_prvni_polo", "Počet gólů v 1. poločasu"),
    ("goly_druhy_polo", "Počet gólů ve 2. poločasu"),
    ("goly_tymu_prvni_polo", "Počet gólů týmu v 1. poločasu"),
    ("goly_tymu_druhy_polo", "Počet gólů týmu ve 2. poločasu"),
    ("prvni_polo_bez_remizy", "Výsledek 1. poločasu bez remízy"),
    ("druhy_polo_bez_remizy", "Výsledek 2. poločasu bez remízy"),
    ("oba_prvni_polo", "Každý tým dá v 1. poločasu"),
    ("hc_prvni_polo_dup", "Handicap 1. poločas"),
]
